version: "3.9"
services:
    db:
        ports:
            - "1433:1433"
        image: "mcr.microsoft.com/azure-sql-edge"
        environment:
            SA_PASSWORD: "_"
            ACCEPT_EULA: "Y"