version: "3.9"
services:
    db:
        ports:
            - "1436:1433"
        image: "mcr.microsoft.com/azure-sql-edge"
        environment:
            SA_PASSWORD: "Password123"
            ACCEPT_EULA: "Y"
            



        